nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    DATA_MANAGEMENT_URL: https://pip-data-management.platform.hmcts.net
    SECRETS_DIRECTORY: /mnt/secrets/pip-shared-kv
    OIDC: true
    FRONTEND_URL: https://${SERVICE_FQDN}

