version: '2'

services:
  pip-frontend:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sdshmctspublic.azurecr.io/pip/frontend
    ports:
      - 8080:8080
  redis:
    image: redis
    ports:
      - 6379:6379
