version: '2'

services:
  pip-frontend:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sdshmctspublicsbox.azurecr.io/pip/frontend:latest
    ports:
      - 8080:8080
