name: Check PR title
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: deepakputhraya/action-pr-title@master
      with:
        regex: '^(PUB-[0-9]{3} [a-zA-Z0-9._\- ]+)|(\[Snyk\].+)$' # Regex the title should match.
        allowed_prefixes: 'PUB-,[Snyk]' # title should start with the given prefix
        prefix_case_sensitive: true # title prefix are case insensitive:
    - name: running linting
      uses: actions/checkout@v2
      run: |
        cd ..
        yarn lint
  ciChecks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: |
          cd ..
          yarn cichecks
